import { HomepageProps } from "../../contracts/components/Homepage";

export const Homepage = ({footerHeight}: HomepageProps) => {
    return <div style={{marginBottom: footerHeight + 30}}>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porta lectus vitae finibus porttitor. Nunc massa orci, laoreet ut justo dignissim, sodales dignissim sem. Vestibulum varius ornare nulla vel feugiat. Duis eleifend varius placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis odio ex, accumsan a porta ac, condimentum sed sem. Duis a ligula diam. Ut sollicitudin lectus ac dapibus tincidunt. Suspendisse non sapien aliquam mauris accumsan lacinia. Nulla tincidunt eros sit amet mauris ultrices, et ultrices nulla congue. Mauris ut mi ac eros pretium malesuada eu sed ligula. Ut feugiat ipsum vehicula auctor finibus. Donec scelerisque augue eu nisl sagittis volutpat. Aliquam sit amet enim vitae sapien sodales lobortis eget pellentesque diam.

Maecenas condimentum tortor dui, nec feugiat nisl faucibus in. Donec purus nibh, pretium ac tortor ac, vehicula elementum ipsum. Cras vitae risus dapibus, luctus tortor cursus, scelerisque felis. Nulla auctor, risus a tempus porttitor, justo nibh accumsan metus, vitae imperdiet sem nulla vel purus. Pellentesque congue malesuada diam quis aliquam. Aliquam erat purus, hendrerit nec purus in, molestie blandit nunc. Vivamus pharetra lorem odio, ac scelerisque elit facilisis sed. Curabitur varius maximus mi, ut hendrerit diam varius at. Maecenas dapibus ullamcorper eros ac maximus. Proin vel lorem feugiat, posuere risus nec, euismod ligula.

Donec laoreet lacus ac viverra interdum. Aliquam non libero sollicitudin, laoreet eros sit amet, viverra quam. Morbi facilisis sapien enim, et ultricies risus dapibus quis. Nulla sit amet nisi sed elit efficitur pellentesque auctor id justo. Duis pulvinar ex accumsan mattis congue. Nunc iaculis tristique elit non laoreet. Vestibulum hendrerit commodo orci eget condimentum. Aenean eget laoreet odio, feugiat dignissim ipsum. Nullam pulvinar, arcu non suscipit luctus, arcu eros faucibus sapien, a dapibus ex ante condimentum odio. Nunc ullamcorper luctus odio, auctor ultricies ante pharetra ut. Donec nec sodales lectus. Aenean a eros at massa efficitur consequat nec ut turpis.

Nunc ultrices pretium mi a tempor. Mauris quis porttitor nisi. Nulla tempor tempor tincidunt. Aliquam semper augue sit amet dignissim facilisis. Cras pulvinar, mauris id auctor auctor, mi turpis tempor sem, vitae laoreet purus nisi nec nibh. Sed eu felis justo. Sed nec enim ac libero vestibulum dictum. Duis bibendum nisl sed risus rhoncus, at malesuada risus lacinia. Suspendisse sed lorem neque. Integer luctus diam vel sem sodales luctus.

Duis vestibulum elit sed feugiat molestie. In ullamcorper ultricies leo, nec faucibus lacus. Sed tincidunt ornare justo non ornare. Sed placerat, massa at laoreet lobortis, risus lorem pharetra lorem, in venenatis tellus sem sed lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec tristique sagittis diam. Nulla viverra enim quis ante sagittis scelerisque. Aliquam erat volutpat. Pellentesque fermentum ante vel arcu tempor, non rhoncus quam tincidunt. Pellentesque ultrices at dui a iaculis. Vivamus venenatis, justo eu consectetur iaculis, massa sapien blandit odio, sit amet vulputate urna orci nec est.

Nulla dapibus malesuada mi et interdum. Fusce eget mauris iaculis est rutrum pulvinar nec sed odio. Duis pharetra sit amet neque nec hendrerit. Cras est ligula, fermentum sed faucibus et, tincidunt eget lorem. Vivamus nec egestas justo, ac consequat augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor est enim, vel laoreet diam condimentum vitae. Nunc posuere metus id lacus vulputate lacinia. Integer sit amet orci lacus. Sed lobortis purus justo, vel aliquet augue sagittis non. Morbi viverra sagittis turpis, ut interdum urna viverra eu. Duis pulvinar gravida ante vitae tincidunt. Duis non mauris in ante finibus commodo. Donec non metus quis ligula molestie ullamcorper.

In accumsan lacus ac est faucibus, a dictum nunc ultricies. Morbi sollicitudin semper elit sed efficitur. Sed in nisl magna. Donec libero urna, hendrerit ac volutpat eu, posuere ac purus. Nam placerat viverra convallis. Sed non eros sapien. Nam non sapien tincidunt, tincidunt ipsum quis, pulvinar elit. Duis vel neque at magna lobortis fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porta lectus vitae finibus porttitor. Nunc massa orci, laoreet ut justo dignissim, sodales dignissim sem. Vestibulum varius ornare nulla vel feugiat. Duis eleifend varius placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis odio ex, accumsan a porta ac, condimentum sed sem. Duis a ligula diam. Ut sollicitudin lectus ac dapibus tincidunt. Suspendisse non sapien aliquam mauris accumsan lacinia. Nulla tincidunt eros sit amet mauris ultrices, et ultrices nulla congue. Mauris ut mi ac eros pretium malesuada eu sed ligula. Ut feugiat ipsum vehicula auctor finibus. Donec scelerisque augue eu nisl sagittis volutpat. Aliquam sit amet enim vitae sapien sodales lobortis eget pellentesque diam.

Maecenas condimentum tortor dui, nec feugiat nisl faucibus in. Donec purus nibh, pretium ac tortor ac, vehicula elementum ipsum. Cras vitae risus dapibus, luctus tortor cursus, scelerisque felis. Nulla auctor, risus a tempus porttitor, justo nibh accumsan metus, vitae imperdiet sem nulla vel purus. Pellentesque congue malesuada diam quis aliquam. Aliquam erat purus, hendrerit nec purus in, molestie blandit nunc. Vivamus pharetra lorem odio, ac scelerisque elit facilisis sed. Curabitur varius maximus mi, ut hendrerit diam varius at. Maecenas dapibus ullamcorper eros ac maximus. Proin vel lorem feugiat, posuere risus nec, euismod ligula.

Donec laoreet lacus ac viverra interdum. Aliquam non libero sollicitudin, laoreet eros sit amet, viverra quam. Morbi facilisis sapien enim, et ultricies risus dapibus quis. Nulla sit amet nisi sed elit efficitur pellentesque auctor id justo. Duis pulvinar ex accumsan mattis congue. Nunc iaculis tristique elit non laoreet. Vestibulum hendrerit commodo orci eget condimentum. Aenean eget laoreet odio, feugiat dignissim ipsum. Nullam pulvinar, arcu non suscipit luctus, arcu eros faucibus sapien, a dapibus ex ante condimentum odio. Nunc ullamcorper luctus odio, auctor ultricies ante pharetra ut. Donec nec sodales lectus. Aenean a eros at massa efficitur consequat nec ut turpis.

Nunc ultrices pretium mi a tempor. Mauris quis porttitor nisi. Nulla tempor tempor tincidunt. Aliquam semper augue sit amet dignissim facilisis. Cras pulvinar, mauris id auctor auctor, mi turpis tempor sem, vitae laoreet purus nisi nec nibh. Sed eu felis justo. Sed nec enim ac libero vestibulum dictum. Duis bibendum nisl sed risus rhoncus, at malesuada risus lacinia. Suspendisse sed lorem neque. Integer luctus diam vel sem sodales luctus.

Duis vestibulum elit sed feugiat molestie. In ullamcorper ultricies leo, nec faucibus lacus. Sed tincidunt ornare justo non ornare. Sed placerat, massa at laoreet lobortis, risus lorem pharetra lorem, in venenatis tellus sem sed lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec tristique sagittis diam. Nulla viverra enim quis ante sagittis scelerisque. Aliquam erat volutpat. Pellentesque fermentum ante vel arcu tempor, non rhoncus quam tincidunt. Pellentesque ultrices at dui a iaculis. Vivamus venenatis, justo eu consectetur iaculis, massa sapien blandit odio, sit amet vulputate urna orci nec est.

Nulla dapibus malesuada mi et interdum. Fusce eget mauris iaculis est rutrum pulvinar nec sed odio. Duis pharetra sit amet neque nec hendrerit. Cras est ligula, fermentum sed faucibus et, tincidunt eget lorem. Vivamus nec egestas justo, ac consequat augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent tempor est enim, vel laoreet diam condimentum vitae. Nunc posuere metus id lacus vulputate lacinia. Integer sit amet orci lacus. Sed lobortis purus justo, vel aliquet augue sagittis non. Morbi viverra sagittis turpis, ut interdum urna viverra eu. Duis pulvinar gravida ante vitae tincidunt. Duis non mauris in ante finibus commodo. Donec non metus quis ligula molestie ullamcorper.

In accumsan lacus ac est faucibus, a dictum nunc ultricies. Morbi sollicitudin semper elit sed efficitur. Sed in nisl magna. Donec libero urna, hendrerit ac volutpat eu, posuere ac purus. Nam placerat viverra convallis. Sed non eros sapien. Nam non sapien tincidunt, tincidunt ipsum quis, pulvinar elit. Duis vel neque at magna lobortis fermentum.
    </div>;
}